services:
  db:
    image: postgres:18-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: db_invoice
    volumes:
      - pgdata:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d db_invoice"]
      interval: "5s"
      timeout: "5s"
      retries: 10

  server:
    build: ./server
    ports:
      - "8080:8080"
    environment:
      DB_HOST: db
      DB_PORT: "5432"
      DB_USER: postgres
      DB_PASS: postgres
      DB_NAME: db_invoice
      JWT_SECRET: "1e5603342a6bc03ad351dbb65197c0038353383f357112aa2a794f2d9593bd29"
    depends_on:
      db:
        condition: service_healthy

  client:
    build: ./client
    ports:
      - "3000:3000"
    environment:
      NEXT_PUBLIC_API_URL: http://localhost:8080
    depends_on:
      - server

volumes:
  pgdata:
